# Default values for travis-live.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 1
restartPolicy: Never

# Evaluated by the post-install hook
sleepyTime: "10"

image: 
  repository: quay.io/travisci/travis-live
  tag: "8321952"
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP
  port: 80
  nodePort: ""

podAnnotations: {}

resources: {}

nodeSelector: {}